spring:
  application:
    name: mspedido
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5673
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/mspedido
    username: admin
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${MSAUTH_SERVER:localhost}:8087
      client:
        registration:
          mspedido-client:
            provider: spring-auth-server
            client-id: ${MSPEDIDO_CLIENT_ID:mspedido-system-client}
            client-secret: ${MSPEDIDO_CLIENT_SECRET:123}
            authorization-grant-type: client_credentials
            scope: internal
        provider:
          spring-auth-server:
            token-uri: http://${MSAUTH_SERVER:localhost}:8087/oauth2/token
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  override-with-generic-response: false

mq:
  queues:
    produto:
      v1:
        pedido-criado:
          estoque-baixa: ${MQ_PEDIDO_CRIADO:produto.v1.pedido-criado.estoque-baixa}
        pedido-cancelado:
          estoque-repor: ${MQ_PEDIDO_CANCELADO:produto.v1.pedido-cancelado.estoque-repor}