spring:
  application:
    name: msproduto
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
h2:
  console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:cursoms-eureka-user@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  override-with-generic-response: false
mq:
  queues:
    produto.v1.pedido-criado.estoque-baixa: produto.v1.pedido-criado.estoque-baixa