spring:
  application:
    name: msproduto
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/msproduto
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:cursoms-eureka-user@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  override-with-generic-response: false
mq:
  queues:
    produto:
      v1:
        pedido-criado:
          estoque-baixa: produto.v1.pedido-criado.estoque-baixa
        pedido-cancelado:
          estoque-repor: produto.v1.pedido-cancelado.estoque-repor