spring:
  application:
    name: msuser
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/msuser
    username: admin
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${MSAUTH_SERVER:localhost}:8087
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
springdoc:
  override-with-generic-response: false